### ISSUE TITLE
your results presented at here is not the same in your paper

### ISSUE THREAD

**Issue by ynuwm** [ramakanth-pasunuru/video_captioning_rl#7]
can you check your results, thank you

**Comment by ramakanth-pasunuru** [comment]
If you see the bold note mentioned in the readme below the results table, it clearly says the reasons why the numbers are different from the paper. I am pasting those again here below: 

Note that this released baseline model has several improvements (and significantly better results) w.r.t. our EMNLP17 paper results, due to the following enhancements:

Better visual features: (1) ResNet-152 frame-level features (2) ResNeXt-101 motion features
Used SCST approach instead of MIXER for reinforcement leanring
Used better entailment classifier

**Comment by ynuwm** [comment]
Thank you, I see it.
